### ISSUE TITLE
js 로컬파일 php, input없이 읽어오는 법

### ISSUE THREAD

**Issue by yelimpark** [Rory0304/WebStudyClub#1]
예를 들어 로그인 기능같은거 넣을 때, 서버 구축하기 귀찮아서 txt 파일로 데이터를 저장하고, 불러오고 싶으면 어떻게 해야하나요? 보안상의 이유로 js에서 불가능하다고 읽긴 했지만 확실한지 모르겠어서 질문합니다...

**Comment by Rory0304** [comment]
궁금해서.. 검색해봤는데,

 [여기 참고](https://velog.io/@takeknowledge/%EB%A1%9C%EC%BB%AC%EC%97%90%EC%84%9C-CORS-policy-%EA%B4%80%EB%A0%A8-%EC%97%90%EB%9F%AC%EA%B0%80-%EB%B0%9C%EC%83%9D%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0-3gk4gyhreu)

다음과 같은 이유로 로컬 파일에 js로는 접근할 수 없을 것 같음.
**로컬시스템에서 로컬 파일 리소스를 요청할 때는 origin(출처)이 null로 넘어가기 때문에 CORS에러가 발생한다.**

**Comment by Rory0304** [comment]
1. 실제로 아래의 js 코드를 실행해보려 했으나..
```
function login() {
        let id = document.querySelector("#id");
        let pw = document.querySelector("#pw");

        var rawFile = new XMLHttpRequest();
        rawFile.open("GET", "./data.txt", true);
        rawFile.onreadystatechange = function () {
          if (rawFile.readyState === 4) {
            if (rawFile.status === 200 || rawFile.status == 0) {
              var allText = rawFile.responseText;
              alert(allText);
            }
          }
        };
        rawFile.send(null);
      }
```
다음과 같은 오류가 발생해버림..

> Access to XMLHttpRequest at 'file:///C:/Users/user/Documents/data.txt' from origin 'null' has been blocked by CORS policy

2. 로컬 파일에 접근할 수 있는 또 다른 방법으로 ActiveXObject 가 있던데..이건 인터넷 익스플로러에서만 사용 가능. 

3. 로컬 파일을 아예 생성해버리는 건 어떨까 해서 찾아 봤는데..
```
 var data = new Blob([text], {type: 'text/plain'}); 
```
이건 파일 생성해서 다운받는 기능. 로컬 파일에 접근할 수 있는 건 아니였음.

**Comment by yelimpark** [comment]
감사합니다~ 조교님 자스로 못하는게 없다더니... :/
